language: python

dist: bionic

python:
  - "3.9"

before_install:
  - curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.1.15 python3 -

install:
  - PIPENV_IGNORE_VIRTUALENVS=1 make dependencies

script:
  - make test

after_success:
  - make cov-reports && poetry run codecov
